root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/admin ./cmd/gatus-admin"
  bin = "./tmp/admin"
  include_ext = ["go", "html", "css"]
  exclude_dir = ["tmp", "data", "config"]
  delay = 500

[misc]
  clean_on_exit = true
